/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  sidebar: [
    { type: "doc", id: "introduction" },
    {
      type: "category",
      label: "Getting started",
      collapsed: false,
      items: [{ type: "doc", id: "introduction/hello-podium" }],
    },
    {
      type: "category",
      label: "Guides",
      collapsed: false,
      items: [
        { type: "doc", id: "guides/assets" },
        { type: "doc", id: "guides/context" },
        { type: "doc", id: "guides/fallbacks" },
        { type: "doc", id: "guides/proxying" },
        { type: "doc", id: "guides/passing-values-to-podlets" },
        { type: "doc", id: "guides/client-side-communication" },
        { type: "doc", id: "guides/redirects" },
        { type: "doc", id: "guides/layout-development" },
        { type: "doc", id: "guides/podlet-development" },
        { type: "doc", id: "guides/hybrid" },
        { type: "doc", id: "guides/browser-extension" },
      ],
    },
    {
      type: "category",
      label: "Reference",
      items: [{ type: "autogenerated", dirName: "api" }],
    },
  ],
};

module.exports = sidebars;
