/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  sidebar: [
    { type: "doc", id: "introduction" },
    {
      type: "category",
      label: "Getting started",
      collapsed: false,
      items: [
        { type: "doc", id: "introduction/hello-podium" },
        { type: "doc", id: "introduction/assets" },
        { type: "doc", id: "introduction/context" },
      ],
    },
    {
      type: "category",
      label: "Podlet guides",
      collapsed: false,
      items: [
        { type: "doc", id: "podlet/fallbacks" },
        { type: "doc", id: "podlet/proxying" },
        { type: "doc", id: "podlet/local_development" },
        { type: "doc", id: "podlet/podlet_to_podlet_communication" },
      ],
    },
    {
      type: "category",
      label: "Layout guides",
      collapsed: false,
      items: [
        { type: "doc", id: "layout/unavailable_podlets" },
        { type: "doc", id: "layout/dynamic_routes" },
        { type: "doc", id: "layout/local_development" },
        { type: "doc", id: "layout/handling_redirects" },
      ],
    },
    {
      type: "category",
      label: "Reference",
      items: [{ type: "autogenerated", dirName: "api" }],
    },
  ],
};

module.exports = sidebars;
